from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import exception_handler

from authors.apps.articles.response_messages import ERROR_MESSAGES


def core_exception_handler(exc, context):
    # If an exception is thrown that we don't explicitly handle here, we want
    # to delegate to the default exception handler offered by DRF. If we do
    # handle this exception type, we will still want access to the response
    # generated by DRF, so we get that response up front.
    response = exception_handler(exc, context)
    handlers = {
        'ValidationError': _handle_generic_error,
        'ArticleNotFound': _handle_article_not_found,
        'RatingNotFound': _handle_rating_not_found,
        'ReportNotFound': _handle_report_not_found,
        'CommentNotFound': _handle_comment_not_found,
    }
    # This is how we identify the type of the current exception. We will use
    # this in a moment to see whether we should handle this exception or let
    # Django REST Framework do it's thing.
    exception_class = exc.__class__.__name__

    if exception_class in handlers:
        # If this exception is one that we can handle, handle it. Otherwise,
        # return the response generated earlier by the default exception 
        # handler.
        return handlers[exception_class](exc, context, response)

    return response


def _handle_generic_error(exc, context, response):
    # This is about the most straightforward exception handler we can create.
    # We take the response generated by DRF and wrap it in the `errors` key.
    response.data = {
        'errors': response.data
    }

    return response


def _handle_article_not_found(exc, context, response):
    # This is about the most straightforward exception handler we can create.
    # We take the response generated by DRF and wrap it in the `errors` key.
    response = Response({'errors': ERROR_MESSAGES['record not found'].format('article')}, status=status.HTTP_404_NOT_FOUND)

    return response


def _handle_rating_not_found(exc, context, response):
    # This is about the most straightforward exception handler we can create.
    # We take the response generated by DRF and wrap it in the `errors` key.
    response = Response({'errors': ERROR_MESSAGES['record not found'].format('rating')}, status=status.HTTP_404_NOT_FOUND)

    return response

def _handle_report_not_found(exc, context, response):
    # This is about the most straightforward exception handler we can create.
    # We take the response generated by DRF and wrap it in the `errors` key.
    response = Response({'errors': ERROR_MESSAGES['record not found'].format('report')}, status=status.HTTP_404_NOT_FOUND)

    return response

def _handle_comment_not_found(exc, context, response):
    # This is about the most straightforward exception handler we can create.
    # We take the response generated by DRF and wrap it in the `errors` key.
    response = Response({'errors': ERROR_MESSAGES['record not found'].format('comment')}, status=status.HTTP_404_NOT_FOUND)

    return response
